server:
  port: 8080

spring:
  datasource:                                     # 数据源的相关配置
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tik?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      connection-timeout: 30000               # 等待连接池分配连接的最大时间（毫秒），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                         # 最小连接数
      maximum-pool-size: 20                   # 最大连接数
      auto-commit: true                       # 自动提交
      idle-timeout: 600000                    # 连接超时的最大时长（毫秒），超时则会被释放（retired）
      pool-name: DataSourceHikariCP           # 连接池的名字
      max-lifetime: 18000000                  # 连接池的最大生命时长（毫秒），超时则会被释放（retired）
      connection-test-query: SELECT 1
  redis:
    host: localhost
    port: 6379
    database: 0
    password: 123456
  data:
    mongodb:
      host: localhost
      port: 27017
      database: douyi


# MinIO 配置
minio:
  endpoint: http://192.168.1.61:9000      # MinIO服务地址
  fileHost: http://192.168.1.61:9000      # 文件地址host
  bucketName: imooc                      # 存储桶bucket名称
  accessKey: imooc                         # 用户名
  secretKey: imooc123456                     # 密码
  imgSize: 1024                           # 图片大小限制，单位：m
  fileSize: 1024                          # 文件大小限制，单位：m